Refactor: use variant and heap pointer wrapper for data_point, array, and object
trytouca/touca-cpp pull request #128
Opened 2022-03-30 11:26 UTC by cthulhu-irl

These changes are supposed to improve code quality and ease maintenance and usage of `data_point`, `array` and `object`:

 - embracing variant ([mpark-variant](https://conan.io/center/mpark-variant) for c++11/14 and std::variant for 17/20) in data_point
 - add `as_TYPE` const/read-only methods to get `data_point` inner value as a singular type instead of accessing inner value directly
 - introduce `deep_copy_ptr` type to preserve value semantics and rule of 5 automatically
 - use value instead of pointer for `_v` members of `array` and `object`
 - replace `detail::array_t` and `detail::object_t` with `array` and `object` in `data_point` but preserve access mechanisms in `as_array` and `as_object`
 - wrap non-primary types in `data_point` in `deep_copy_ptr` instead of using raw pointers
 - add const begin/end methods to `array` and `object`
 - introduced `overloaded`, `sink` and `generic_overload` variant helper types. (currently unused as `type` method)

2022-03-30 15:57 UTC, ghorbanzade requested changes
I only reviewed the easy parts so far but submitting this review for now. I'll review the good stuff after my meetings today.

2022-03-30 15:57 UTC, ghorbanzade commented on conanfile.py
> +        self.options["mpark-variant"].header_only = True
This package doesn't seem to have `header_only` as option. It only ships as `header_only` any way. See [conan center recipe](https://conan.io/center/mpark-variant).
```suggestion
```

2022-03-30 15:57 UTC, ghorbanzade commented on conanfile.py
> +            "mpark-variant/1.4.0",
Shouldn't this be the alias to the CMake target?
```suggestion
            "mpark_variant::mpark_variant",
```

2022-03-30 15:57 UTC, ghorbanzade commented on include/touca/internal/utils.hpp
> +#if defined(TOUCA_HAS_CPP17) || defined(TUCA_HAS_CPP20)
We only need to check `defined(TOUCA_HAS_CPP17)` here and below.

2022-03-30 15:57 UTC, ghorbanzade commented on src/devkit/comparison.cpp
> +  switch (type) {
I think your branch doesn't have the latest code in upstream. Could you please rebase this branch?

2022-03-30 19:11 UTC, ghorbanzade commented on include/touca/internal/utils.hpp
> +#if defined(TOUCA_HAS_CPP17) || defined(TUCA_HAS_CPP20)
Yes we can. But should we? `TOUCA_HAS_CPP17` is enabled for 17 and newer. What is the benefit of including `|| defined(TUCA_HAS_CPP20)`? Do you think it help with readability?

2022-03-30 20:42 UTC, cthulhu-irl commented on src/devkit/comparison.cpp
> +  switch (type) {
done. (through your guidance)

2022-03-30 20:44 UTC, cthulhu-irl commented on include/touca/internal/utils.hpp
> +#if defined(TOUCA_HAS_CPP17) || defined(TUCA_HAS_CPP20)
I think it does and also I have a typo... but since intend is as you said, I'll remove the second... I thought naming wasn't descriptive, but you're right... it's redundant...

2022-03-31 16:17 UTC, mapron commented on include/touca/core/types.hpp
> +  data_point(object&& value)
Why move constructor is missing 'noexcept' specifier? is it intentional?

2022-03-31 16:22 UTC, mapron commented on include/touca/internal/variant_helpers.hpp
> +  constexpr sink(Args&&...) noexcept {}
good :)

2022-03-31 16:52 UTC, ghorbanzade approved these changes

2022-03-31 17:46 UTC, cthulhu-irl commented on include/touca/internal/utils.hpp
> +  const value_type&& operator[](const std::size_t index) const&& noexcept {
I've heard there was something with std::cref, I don't remember what it was though... but I went for 3 others, this one seemed to better be there...

2022-03-31 17:48 UTC, cthulhu-irl commented on include/touca/core/types.hpp
> +  data_point(object&& value)
yes. even though it's a move, but it initializes `deep_copy_ptr<object>` which uses `new`. same with `data_point(array&&)`.

2022-03-31 18:24 UTC, mapron commented on include/touca/core/types.hpp
> +  data_point(object&& value)
can't we just grab unique_ptr from && object and don't allocate?

2022-03-31 18:25 UTC, mapron commented on include/touca/internal/utils.hpp
> +  deep_copy_ptr(deep_copy_ptr&& other) noexcept = default;
wait, move of deep_copy_ptr do not allocate!

2022-03-31 18:26 UTC, mapron commented on include/touca/core/types.hpp
> +  data_point(object&& value)
deep_copy_ptr && do not use new, I saw that! :D

2022-03-31 19:59 UTC, cthulhu-irl commented on include/touca/core/types.hpp
> +  data_point(object&& value)
`data_point(object&&)` calls `deep_copy_ptr<object>(object&&)` which is the first constructor overload... `deep_copy_ptr<object>(Args&& ...args)`

2022-03-31 23:01 UTC, mapron commented on include/touca/core/types.hpp
> +  data_point(object&& value)
and move of deep_copy just moves unique_ptr. Where am I wrong? It's zero allocation. noexcept.

2022-03-31 23:04 UTC, mapron commented on include/touca/core/types.hpp
> +  data_point(object&& value)
I see. It calls move from object to object inside deep_copy_ptr. We have no deep_copy_ptr at the source to move from. My bad. Code is totally correct.

2022-04-01 04:02 UTC, ghorbanzade requested changes
I really enjoyed reviewing this PR. There were a few things that made me go search the internet, read articles and learn a few things in the process. Thanks for that! Really happy with the quality and direction of your changes.

I made a few comments. They are nitpicks to make proposed changes more consistent with the rest of the code base. I'd love to see them addressed before merging this PR.

Once merged, I'm really motivated to think about ways to clean up the `as_<type>` functions and the long list of `data_point` constructors. But we should definitely tackle that as a separate PR.

Cannot wait to see this merged! Thank you.

2022-04-01 10:54 UTC, cthulhu-irl commented on include/touca/core/types.hpp
> +  variant_type _value;
right. it wasn't supposed to be there. fixed.

2022-04-01 11:21 UTC, cthulhu-irl commented on include/touca/core/types.hpp
> +class TOUCA_CLIENT_API data_point {
actually it shouldn't have been there in the first place, I added it in my last PR due non-virtual destructor, but it was unnecessary.

2022-04-01 11:27 UTC, cthulhu-irl commented on src/devkit/comparison.cpp
> +      break;  // unhandled
done.

2022-04-01 11:58 UTC, cthulhu-irl commented on include/touca/internal/utils.hpp
> +};
done. thought prefixing by `_` is UB, but apparently it's UB if `__` or `_<starting-by-upper-case>`

2022-04-01 13:51 UTC, ghorbanzade commented on include/touca/internal/utils.hpp
> +};
Yeah, we don't need to worry about UB in this case. Thanks for making the change.

2022-04-01 13:52 UTC, ghorbanzade commented on include/touca/core/types.hpp
> +class TOUCA_CLIENT_API data_point {
I see. Thanks for the explanation. Good as is (without final) then.

2022-04-01 15:59 UTC, cthulhu-irl commented on include/touca/internal/utils.hpp
> +#endif  // different variant implementations for different standards
1. sure.
2. internal isn't as same as detail... it's intended to be exposed to all other units in the current codebase but not user. detail is detail of a single or a set of units, local to them and not other units. though that's my own interpretation, if you insist on changing it to detail, I'll agree.
3. `internal/utils.hpp` and `internal/variant_helpers.hpp` aren't the same, and neither belong to `core/`. there is also `deep_copy_ptr` in `utils.hpp` which isn't about variant.

2022-04-01 16:23 UTC, ghorbanzade commented on include/touca/internal/utils.hpp
> +#endif  // different variant implementations for different standards
2. Yes, I've seen and worked with so many different interpretations. You are not wrong. We're just using a different convention and I apologize if this is not properly documented yet:
- File hierarchy: The files in `core` are whatever is _necessary_ for building the core of the library (with the exception of `schema.hpp` which is in `impl`). `core` does not include the low-level Client API either which resides in `client/detail`. We've moved those headers to `detail` sub-directory to emphasize that these header files are not user facing and should not be directly included. The files in `devkit` are used for other components including the low-level CLI, the test framework and the Comparator (which is not in this repo). So in some ways, we consider `core` as `internal`.
- Namespaces: We just don't make distinction between `internal` and `detail`. Everything that is not meant to be used by other library components resides in `detail`. See `filesystem.hpp`, `types.hpp`, and some parts of `serializer.hpp`.
3. I understand we can chunk these things into different pieces and be right every time. It's a game of compromises. Some teams like many small files, some prefer a few large files. The balance is always somewhere in-between. I understand these thins are separate and you are right that `deep_copy_ptr` doesn't need to be in `variant.hpp` but since they are small in code size, let's merge them together. We can always unbundle them when they get to a certain level of complexity.

2022-04-01 18:54 UTC, ghorbanzade approved these changes
Looking great! Thank you @cthulhu-irl for these improvements!

2022-04-01 18:57 UTC, merged